apiVersion: v1
kind: Service
metadata:
  name: circle-calculator-service
  namespace: circle-calc
spec:
  type: NodePort
  selector:
    app: circle-calculator
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30080
